### ISSUE TITLE
Error while executing kube-bind

### ISSUE THREAD

**Issue by banicr** [kube-bind/kube-bind#142]
I am facing the below error while executing `kubectl bind https://mangodb.com/exports`
```
 % kubectl bind https://mangodb.com/exports 
DISCLAIMER: This is a prototype. It will change in incompatible ways at any time.

Error: failed to fetch authentication url "https://mangodb.com/exports": invalid character '<' looking for beginning of value
```

kubectl version: `v1.23.6`
cluster: `EKS`

Can anyone please help me resolve this error. TIA

**Comment by banicr** [comment]
Hi @pkbhowmick 
Thanks for your reply, I setup the dex locally and I am testing the usecases. it looks like  `instance status updated upstream is updated downstream` is not working. Am I missing something here??

**Comment by pkbhowmick** [comment]
Hi @banicr 
Can you please share more information so that I can reproduce it?

**Comment by banicr** [comment]
Hi @pkbhowmick 

I am creating a MangoDB CR from consumer please find the below `mangodb-cr.yaml` file
```
apiVersion: mangodb.com/v1alpha1
kind: MangoDB 
metadata:
  name: test
spec: 
    tier: dedicated
status:
    phase: Running
```
I am trying to update the status from `phase: Running` to `phase: Pending` in `Provider cluster` but it is not getting updated in `consumer cluster`

I am expecting status update from Provider cluster should get reflected in consumer cluster.

**Comment by pkbhowmick** [comment]
Hi @banicr 
Please make sure, you are running example backend in provider cluster/ using provider kubeconfig and konnector pods are running in consumer cluster.

**Comment by pkbhowmick** [comment]
Can you please make sure that MangoDB object is really created in kube-bind-r86l2-default ns in provider cluster?

**Comment by banicr** [comment]
Yes, its created

**Comment by pkbhowmick** [comment]
Interesting, but the error says, it can't find the provider cluster's object. Let me re-produce the bug and get back to you.

**Comment by pkbhowmick** [comment]
Hi @banicr 
I can reproduce the bug. It is occurred because of status field is not marked as sub resource in MangoDB crd. https://github.com/kube-bind/kube-bind/blob/main/deploy/examples/crd-mangodb.yaml

But from code, status is tried to update using `UpdateStatus` method. https://github.com/kube-bind/kube-bind/blob/main/pkg/konnector/controllers/cluster/serviceexport/status/status_controller.go#L109

I have quick fix for the issue. You can edit ApiServiceExport from your provider cluster and add the status in subresource part like below:
```
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: MangoDB
    listKind: MangoDBList
    plural: mangodbs
    singular: mangodb

```

To update apiservice export:

```
kubectl edit apiserviceexport mangodbs.mangodb.com -n <provider-ns>
``` 

Konnector will update the crd in consumer cluster according to the provider cluster apiserviceexport. Then you will find the expected status in consumer side.
