### ISSUE TITLE
Add reference to PermissionClaims sub-api

### ISSUE THREAD

**Issue by cnvergence** [kube-bind/kube-bind#257]

**Comment by mjudeikis** [comment]
One example where this doesn ot work is here:
```
Some real life example usecase:

1. Im trying to create cert-manager as service. My certificaste object looks like this:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: server-cert 
  namespace: default
spec:
  commonName: server-cert
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: kcp-ca
  secretName: server-cert-tls
  secretTemplate:
    labels:
      kube-bind.io/targeted: "true"
```

and my template would look like:
```yaml
apiVersion: kube-bind.io/v1alpha2
kind: APIServiceExportTemplate
metadata:
  name: certificate
spec:
  scope: Namespaced
  resources:
  - group: cert-manager.io
    versions: 
    - v1
    resource: certificates
  permissionClaims:
  - group: ""
    resource: secrets
    selector:
      labelSelector:
        matchLabels:
          controller.cert-manager.io/fao: "true"
          kube-bind.io/targeted: "true"
```

And this is not nice as I basically asking user to provide the selector. I want something like this:

```yaml
apiVersion: kube-bind.io/v1alpha2
kind: APIServiceExportTemplate
metadata:
  name: certificate
spec:
  scope: Namespaced
  resources:
  - group: cert-manager.io
    versions: 
    - v1
    resource: certificates
  permissionClaims:
  - group: ""
    resource: secrets
    selector:
      jsonPaths:
      - name: spec.secretName
         namespace: metadata.namespace
```
so it always pulls once I intended to
